--- #YAML:1.0
name:                Acme-CPANAuthors-Brazilian
version:             0.03
abstract:            We are brazilian CPAN authors
license:             perl
author:              
    - Breno G. de Oliveira <garu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Acme::CPANAuthors:             0
    Test::More:                    0.47
    Test::UseAllModules:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
